### ISSUE TITLE
Íslandsmet: Lóðakast kvenna birtist tvisvar

### ISSUE THREAD

**Issue by bergur** [frjalsar/afrekaskra#13]

**Comment by Izelord** [comment]
Það gefur eitthvað klikkað í Þór þegar innanhús metið var skráð. Það er tvískráð sem bæði innanhús og utanhús. Þess vegna birtist lóðkast tvisvar sinnum í utanhús listanum. Ég fjarlægði línuna úr Metaskrá töflunni í Þór sem átti ekki að vera.
