### ISSUE TITLE
Laga format á tímum

### ISSUE THREAD

**Issue by bergur** [frjalsar/afrekaskra#15]
Ætti alltaf að vera m:ss,msms
 - Ársbesta í 800m kv listað sem 2:5,18 vs. 2:05,18

  - Stundum með leiðandi núll í formattinu, sbr. 05:45,37 vs 5:45,37 

- Stundum punktur í stað kommu

**Comment by Izelord** [comment]
Það á alltaf að vera leiðandi núll ef talan er minni en 10. Það er auðveldara að lesa tímanna þannig. Þetta var rétt gert fyrir klukkustundir og mínútur en hafði gleymist fyrir sekúndur. Tíminn 2 mín og 5,18 sek ætti núna að birtast sem 02:05.18 mm:ss.dd.
