### ISSUE TITLE
400 m hlaup og 400 m grindarhlaup eiga að vera í sek ekki mín.

### ISSUE THREAD

**Issue by bergur** [frjalsar/afrekaskra#27]
Dæmi: 1:00,2 mín ætti að vera 60,2 sek

**Comment by Izelord** [comment]
Hvar birtist 400m tíminn sem mín? Hann á að birtast sem sek og gerir það á öllum þeim stöðum sem ég athugaði.

**Comment by bergur** [comment]
Pottþétt gamalt issue, var ekki vandamál með boðhlaupin? Ef þú sérð þetta ekki, þá lokum við þessu.
