### ISSUE TITLE
Afrek vitlaust skráð

### ISSUE THREAD

**Issue by bergur** [frjalsar/afrekaskra#28]
Póstur frá Sigþóru Brynju

Ég var að spá með í sambandi við afrekskrána. Ég sá að tíminn minn frá því í Búlgaríu í 5000m er skráður undir 3000m en ekki 5000m í afreksskráni og var því topplistinn sem þið birtuð fyrir 5000m vitlaus. Er möguleiki að laga þetta og færa hann undir 5000m tímana?😊

**Comment by Izelord** [comment]
Sýnist vera búið að laga þetta.
