### ISSUE TITLE
Birta öldungamet á prófíl

### ISSUE THREAD

**Issue by bergur** [frjalsar/afrekaskra#42]
Það birtast engin öldungamet hjá íþróttamönnum: https://sif.fri.is/keppandi/48540

**Comment by Izelord** [comment]
Búin að uppfæra kóðann til að ná í 30+ met líka. Þau eru geymd í annari töflu. Þannig að núna tekur lengri tíma fyrir metin að birtast á prófíl síðunni því það þarf fleiri köll í gagnagruninn. Það virðist ekki vera geymdur listi yfir eldri met (óvirk) fyrir 30+.
